### ISSUE TITLE
[FEATURE] 상단바

### ISSUE THREAD

**Issue by Suanna01** [Gongdongjang/consumer_client#48]
## :loudspeaker: 이슈 내용
> 상단바 제작 및 상단바 txt 적용
## :page_with_curl: 상세 내용
- 상단바에 뒤로가기, 지역명, 장바구니 이동 생성
- 지역명 함수 Home.java -> MainActivity.java 이동
- `themes.xml` NoActionBar지정
- 농가, 스토어 페이지/ 상세페이지 Activity에 따라 상단바 txt 변경
## :heavy_check_mark: 체크리스트
- [x] 상단바 추가
- [x]  농가, 스토어 상세페이지 Activity에서 상단바는 지역명 대신 00스토어, 00농가 XXX상품 등으로 변경
- [x] 농가, 스토어 페이지 Activity에서 상단바 지역명 클릭 후 주소 변경 시 초기화면(홈)으로 돌아가기
## :round_pushpin: 참고 내용
[커스텀 액션바](https://game-happy-world.tistory.com/11)
[안드로이드 공식문서](https://developer.android.com/guide/navigation/navigation-ui?hl=ko)
[툴바 include](https://95mkr.tistory.com/entry/ANDROID6)

**Comment by plum-king** [comment]
농 스 제 관련 상단바 제가 수정하였습니다 🤩
