### ISSUE TITLE
[ERROR] 농가, 스토어 관련 에러

### ISSUE THREAD

**Issue by leejw-lu** [Gongdongjang/consumer_client#68]
## :loudspeaker: 이슈 내용
> 농가, 스토어 관련 에러
## :page_with_curl: 상세 내용
-  전체입점 농가에서 이미지 때문에 오류나는 듯
-  농가 상세페이지에서의 운영시간 Hours와 전체입점스토어 운영시간 Hours 에러
## :heavy_check_mark: 체크리스트
- [x] 이미지 해결
- [x] Hours 해결

**Comment by plum-king** [comment]
hours 제가 해결했습니다🤩
